spring.application.name=WebBanPhone
spring.datasource.url=jdbc:sqlserver://KIEUPHAT:1433;databaseName=PhoneShopDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
app.bootstrap.enabled=true

app.cors.allowed-origins=http://localhost:4200,http://127.0.0.1:4200
app.jwt.secret=replace-this-with-a-very-long-secret-key-please-change-in-production
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000
